Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,se"
        Option "XkbVariant" ","
        Option "XkbOptions" "grp:win_space_toggle"
EndSection

Section "InputClass"
        Identifier "Wings Tech Xtrfy M4 Pointer"
        MatchIsPointer "on"
        MatchProduct "Wings Tech Xtrfy M4"
        Driver "libinput"
        Option "AccelSpeed" "-0.99"
EndSection
