[colors.primary]
background = '#282828'
foreground = '#bfbfbf'

[colors.normal]
black   = '#000000'
red     = '#af005f'
green   = '#278001'
yellow  = '#ecb546'
blue    = '#5f80e3'
magenta = '#875fd7'
cyan    = '#005f5f'
white   = '#dadada'

[colors.bright]
black   = '#585858'
red     = '#ff4f4f'
green   = '#87af00'
yellow  = '#d79921'
blue    = '#5fafd7'
magenta = '#f558be'
cyan    = '#8ec07c'
white   = '#5f8787'
